import: definition.yaml

concurrency:
  task:
    # dbbench-std: 5
    # os-std: 5
    # alfworld-std: 5
    webshop-std: 1
  agent:
    llama-2-7b-chat-hf: 1 #gpt-3.5-turbo-0613: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - llama-2-7b-chat-hf #gpt-3.5-turbo-0613
    task:
      # - alfworld-std
      - webshop-std
      # - dbbench-std
      # - os-std

output: "outputs/{TIMESTAMP}"
